version: '3'
services:
  #  To start replica mode please use `docker-init.sh`
  postgres_slave:
    container_name: postgres_slave
    image: postgres:14.5
    restart: always
    volumes:
      - ./data-slave:/var/lib/postgresql/data
      - ./config/postgres.conf:/etc/postgresql/postgresql.conf
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
